### PR TITLE
Skip unused grunt package not available on FreeBSD.

### PR DESCRIPTION
**Pull request by Teetoow**
Remove the use of grunt-mocha package (it seems not be used in production).
This package needs phantomjs which seems to be an unmaintained package.
Since it is no more available under FreeBSD I removed this line. There
is no consequences on the OnlyOffice DocumentServer code.

### CODE REVIEW

**Comment by ShockwaveNN** [comment]
I asked our devs and they said that currently we do not use `grunt-mocha` but planning to add some more test in future, so we don't like idea of complete removal

Could this packaged be OS-dependent and do not installed and called on FreeBSD?

**Comment by Teetoow** [comment]
> I asked our devs and they said that currently we do not use `grunt-mocha` but planning to add some more test in future, so we don't like idea of complete removal

Maybe it is possible to use grunt-mocha by developers during development and don't try to install it on production environment since it is only a package to make some tests?

> Could this packaged be OS-dependent and do not installed and called on FreeBSD?

First thing is that phantonJS seems to be an unmaintained package (that's why it is deprecated):
`npm WARN deprecated phantomjs-prebuilt@2.1.16: this package is now deprecated`

Next it seems that this version depends on libraries which are no more available under FreeBSD:
```
> phantomjs-prebuilt@2.1.16 install /tt/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Unexpected platform or architecture: freebsd/x64
It seems there is no binary available for your platform/architecture
Try to install PhantomJS globally
```

I don't know what to say about that.. Except that it's a package which could be useful for developers and not for end users. Since it is not available on all platforms (at least FreeBSD) it might be interested to think about not installing it on production?

**Comment by ShockwaveNN** [comment]
Thanks for pointing out, we did some research and moved some packages to `devDependencies`, so whey should not be installed on Production environment

https://github.com/ONLYOFFICE/web-apps/commit/74a44dce21bc345bd9035284d9e4361cfd07bdd0

**Comment by maxkadushkin** [comment]
mocha is in dev dependencies now, and phantomjs
close it

**Pull request closed without merging**
