### PR TITLE
Changing the build config to avoid mangling the js bundles.

### PR DESCRIPTION
**Pull request by tomasgodoi**
This will allow the plugins to use more APIs which were obfuscated.

### CODE REVIEW

**Comment by ShockwaveNN** [comment]
Hi, could you change base branch to develop? We are not merging any changes directly to master, thanks

**Comment by ShockwaveNN** [comment]
Am I right - you're trying to solve [issue](https://github.com/ONLYOFFICE/sdkjs-plugins/issues/91)  with single method by completely disabling options?

**Comment by maxkadushkin** [comment]
options you set up have such values by default. that PR only increasing readability

**Comment by maxkadushkin** [comment]
uglifyjs was changed to terser

https://github.com/ONLYOFFICE/web-apps/blob/master/build/Gruntfile.js#L385
https://github.com/ONLYOFFICE/web-apps/blob/master/build/Gruntfile.js#L470

**Pull request closed without merging**
