### PR TITLE
Great improvement of the Spanish translation

### PR DESCRIPTION
**Pull request by adrianlopezgalera**
Hi!

I am a Spanish writer and linguist. I am fascinated with your program. I think it can become the best free (libre) office software. For this reason, I want to contribute to what I know how to do, as well as to propose improvements.

The Spanish translation is just horrible, both in the program and in the online documentation. It contains grammatical, spelling and coherence errors. It makes numerous false friends and unusual terms. It mixes formal and informal language, and personal and impersonal commands (very different in Spanish). As an example, the "tabs" menu is translated as "pestañas" ("eyelash") instead of "tabulador".

I have also found unfinished sentences and confusions like "inner" vs. "outer" produced, perhaps, by copying the same line twice to put it in an automatic translator. I had to review the original text with the program running to understand what the translation meant. I do not want to criticize your good work. I also make many mistakes when writing in English, but a bad translation gives users a bad image.

Therefore, I have decided to correct all the texts of each of the applications.

This request contains the corresponding corrections to the document editor. I look forward to continuing to work on the other applications.

Regards.

### CODE REVIEW

**Comment by adrianlopezgalera** [comment]
Hello again. I'm still working on improving the translation of all components. I am trying very hard to match the same exact strings between the applications so that there is a consistent translation between the word processor, the spreadsheet editor, and the presentation editor.

I know so many changes can be overwhelming and difficult to review (for me too!), but it's necessary to get a job done right.

Regards.

**Review by svetlana81 — COMMENTED** [review]
Hello. 
Thank you for your collaboration.
We reviewed your changes and accepted most of them with some exceptions.
When working with translations, we should make changes in existing files within our internal translation system, so we'll move your changes to the translation system without merging this pull request.
Best regards.

**Comment by adrianlopezgalera** [comment]
> Hello. Thank you for your collaboration. We reviewed your changes and accepted most of them with some exceptions. When working with translations, we should make changes in existing files within our internal translation system, so we'll move your changes to the translation system without merging this pull request. Best regards.

Hi! I continue working on the three applications and I will not have a final version for each component until I have considered, in my opinion, what is the best translation for each string in its context. There are very difficult contexts where it is very hard for the message to be understood clearly or better fit the space.

I understand your way of working, but... how do I know which changes have been accepted or rejected? If a change is rejected, could you tell me the reason in order to think about it and propose alternatives? Without a professional translator or native speaker reviewing your program, it is very likely that dubious translations will continue to appear in your internal system.

I can be wrong when translating, of course, because I am human and English is ambiguous in too many situations. Almost everything can be translated as almost everything. For example, depending on whether a sentence is interpreted as an indication or an advice/command to the user, the translation varies absolutely. If I can't figure out where it appears in the running program, it's easy to make a mistake.

Due to this reason, I take responsibility for scrutinizing every last detail once these translations are integrated into a future version to avoid having introduced a not very successful change, even if it is merely for a matter of style. 

Regards.

**Comment by adrianlopezgalera** [comment]
The Spanish localization is now complete for the three desktop apps (main folder). I'll keep reviewing when the translations are incorporated into the new version.

Regards.

**Comment by adrianlopezgalera** [comment]
Hello. Is there any news? I have been altruistically working on these translations for two weeks and it would be very sad if it had been in vain.

Regards.

**Comment by svetlana81** [comment]
> Hello. Is there any news? I have been altruistically working on these translations for two weeks and it would be very sad if it had been in vain.
> 
> Regards.

Hello. 
We have finished transferring changes to the translation system.
The exceptions are listed below.

Rejected rows for the Document Editor
24 - decided to keep the original phrase
45 - decided to keep the original phrase
66 - decided to keep the original phrase
149 - decided to keep the original phrase
206 - decided to keep the original phrase
240 - decided to keep the original phrase
252 - decided to keep the original phrase
305 - replaced with "Noviembre"
428 - replaced with "Invitado"
682 - decided to keep the original phrase
683 - decided to keep the original phrase (both are synonymous)
685 - decided to keep the original phrase
791 - decided to keep the original phrase
793 - decided to keep the original phrase
795 - decided to keep the original phrase
797 - decided to keep the original phrase
799 - decided to keep the original phrase
801 - decided to keep the original phrase
804 - decided to keep the original phrase
807 - decided to keep the original phrase
814 - decided to keep the original phrase
871 - replaced with "Ha fallado la carga del historial"
1019 - Gráfico circular
1902 - Marco de flujo
2096 - decided to keep the original phrase
3001 - decided to keep the original phrase

Rejected rows for the Presentation Editor:
274 - decided to keep the original phrase for brevity
331 - decided to keep the original phrase for brevity
365 - decided to keep the original phrase for brevity
377 - decided to keep the original phrase for brevity
520 - replaced with "Invitado"
769 - decided to keep the original phrase
770 - decided to keep the original phrase (both are synonymous)
772 - decided to keep the original phrase
804 - decided to keep the original phrase
811 - decided to keep the original phrase
854 - decided to keep the original phrase
856 - decided to keep the original phrase
858 - decided to keep the original phrase
860 - decided to keep the original phrase
864 - decided to keep the original phrase
868 - decided to keep the original phrase
870 - decided to keep the original phrase
1175 - decided to keep the original phrase
1774 - replaced with "Situar corchetes a la altura del argumento"

Rejected rows for the Spreadsheet Editor:
124 - decided to keep the original phrase for brevity
181 - decided to keep the original phrase for brevity
215 - decided to keep the original phrase for brevity
227 - decided to keep the original phrase for brevity
632 - decided to keep the original phrase
633 - decided to keep the original phrase (both are synonymous)
635 - decided to keep the original phrase
977 - decided to keep the original phrase
979 - decided to keep the original phrase
981 - decided to keep the original phrase
983 - decided to keep the original phrase
988 - decided to keep the original phrase
991 - decided to keep the original phrase
998 - decided to keep the original phrase
3482 - decided to keep the original phrase

**Comment by adrianlopezgalera** [comment]
Hello!

Document Editor
24 - decided to keep the original phrase => OK (I put the adjective in feminine to maintain agreement with the word "alineación"). 
45 - decided to keep the original phrase => OK (I put the adjective in feminine to maintain agreement with the word "alineación")
66 - decided to keep the original phrase => OK (I put the adjective in feminine to maintain agreement with the word "alineación")
149 - decided to keep the original phrase => OK
206 - decided to keep the original phrase => OK
240 - decided to keep the original phrase => OK
252 - decided to keep the original phrase => OK
305 - replaced with "Noviembre" => OK (my mistake)
428 - replaced with "Invitado" => OK
682 - decided to keep the original phrase => "Elipsis horizontal" sounds as a literal translation. I have never seen a native Spanish speaker call it that. Just look up: https://es.wikipedia.org/wiki/Puntos_suspensivos
683 - decided to keep the original phrase (both are synonymous) => "Guion largo" (now "guion" is written always without an accent by new rule of the RAE) is ambiguous because there are people who call the en-dash that. The "raya" avoids this problem because all writers know that it is the symbol for dialogues in Spanish.
685 - decided to keep the original phrase => I added the distinction for the above reason
791 - decided to keep the original phrase  => OK (but in infinitive sounds more native when the action has not started, as a window title).
793 - decided to keep the original phrase  => OK (I added the distinction for the above reason)
795 - decided to keep the original phrase  => OK (I added the distinction for the above reason)
797 - decided to keep the original phrase  => OK (I added the distinction for the above reason)
799 - decided to keep the original phrase  => OK (I added the distinction for the above reason)
801 - decided to keep the original phrase  => OK (I added the distinction for the above reason)
804 - decided to keep the original phrase  => OK (I added the distinction for the above reason)
807 - decided to keep the original phrase  => OK (I added the distinction for the above reason)
814 - decided to keep the original phrase  => OK (I added the distinction for the above reason)
871 - replaced with "Ha fallado la carga del historial"  => OK (my mistake)
1019 - Gráfico circular  => OK (It's better now)
1902 - Marco de flujo  => OK (It's better now)
2096 - decided to keep the original phrase  => OK
3001 - decided to keep the original phrase  => OK (I got confused with the above string).

Rejected rows for the Presentation Editor:
274 - decided to keep the original phrase for brevity => OK
331 - decided to keep the original phrase for brevity => OK
365 - decided to keep the original phrase for brevity => OK
377 - decided to keep the original phrase for brevity => OK
520 - replaced with "Invitado" => OK
769 - decided to keep the original phrase => Same as above
770 - decided to keep the original phrase (both are synonymous) => Same as above
772 - decided to keep the original phrase => Same as above
804 - decided to keep the original phrase => OK (I added the distinction for the above reason)
811 - decided to keep the original phrase => OK (I added the distinction for the above reason)
854 - decided to keep the original phrase => OK (I added the distinction for the above reason)
856 - decided to keep the original phrase => OK (I added the distinction for the above reason)
858 - decided to keep the original phrase => OK (I added the distinction for the above reason)
860 - decided to keep the original phrase => OK (I added the distinction for the above reason)
864 - decided to keep the original phrase => OK (I added the distinction for the above reason)
868 - decided to keep the original phrase => OK (I added the distinction for the above reason)
870 - decided to keep the original phrase => OK (I added the distinction for the above reason)
1175 - decided to keep the original phrase => OK (I added the distinction for the above reason)
1774 - replaced with "Situar corchetes a la altura del argumento" => OK (my mistake)

Rejected rows for the Spreadsheet Editor:
124 - decided to keep the original phrase for brevity => OK
181 - decided to keep the original phrase for brevity => OK
215 - decided to keep the original phrase for brevity => OK
227 - decided to keep the original phrase for brevity => OK
632 - decided to keep the original phrase => Same as above
633 - decided to keep the original phrase (both are synonymous) => Same as above
635 - decided to keep the original phrase => Same as above
977 - decided to keep the original phrase => OK (I added the distinction for the above reason)
979 - decided to keep the original phrase => OK (I added the distinction for the above reason)
981 - decided to keep the original phrase => OK (I added the distinction for the above reason)
983 - decided to keep the original phrase => OK (I added the distinction for the above reason)
988 - decided to keep the original phrase => OK (I added the distinction for the above reason)
991 - decided to keep the original phrase => OK (I added the distinction for the above reason)
998 - decided to keep the original phrase => OK (I added the distinction for the above reason)
3482 - decided to keep the original phrase => OK (my mistake)

Thank you very much for your work and for taking the trouble to show me the rejected changes. I have stated my reasons if you want to reflect on it.

Regards.

**Comment by svetlana81** [comment]
> 682 - decided to keep the original phrase => "Elipsis horizontal" sounds as a literal translation. I have never seen a native Spanish speaker call it that. Just look up: https://es.wikipedia.org/wiki/Puntos_suspensivos
> 683 - decided to keep the original phrase (both are synonymous) => "Guion largo" (now "guion" is written always without an accent by new rule of the RAE) is ambiguous because there are people who call the en-dash that. The "raya" avoids this problem because all writers know that it is the symbol for dialogues in Spanish.

Hello.
We have changed these phrases in the translation system.
Elipsis horizontal -> Puntos suspensivos
Guion largo -> Raya
Thank you.
Best regards.

**Comment by JuliaRadzhabova** [comment]
Transfer of changes to the translation system is completed.

**Pull request closed without merging**
