### PR TITLE
Enforce GNU Affero License, revert commit 19e4859

### PR DESCRIPTION
**Pull request by JasonCoombs**
// The GNU Affero License prohibits "SaaSS" denial of service to any user of a copy of this AGPL-licensed version of this "covered work"
        // A developer who has a private license to this "covered work" may insert any license restrictions they wish into this function.
        // See: https://www.gnu.org/licenses/why-affero-gpl.html
        // AGPL 3.0 License: https://github.com/ONLYOFFICE/web-apps/blob/master/LICENSE.txt

### CODE REVIEW

**Comment by ShockwaveNN** [comment]
Wow, this looks radical

Could you clarify?

**Comment by JasonCoombs** [comment]
> Wow, this looks radical
> 
> Could you clarify?

See: https://medium.com/@onlyoffice/answers-to-all-your-questions-about-mobile-onlyoffice-e19eefd7b7c2

https://www.reddit.com/r/selfhosted/comments/fpurk6/stop_recommending_onlyoffice/

https://github.com/ONLYOFFICE/DocumentServer/issues/805#issuecomment-602622874

SUMMARY: although the Only Office Team DOES have the legal right under the terms of the GNU Affero GPL 3.0 to fork their own copyright-protected source code to create a non-free version, something for which they should never be accused of any wrongdoing and they should be supported by paying customers and thanked for their good and valuable works, the one thing they can NEVER do is what they did in commit 19e4859e1051fe16697272be3bacaacc06cc9f40

Only Office Team cannot insert into the AGPL-licensed repository the lines of source code they inserted which disable functionality and impose a forced private licensing scheme. Apparently the four editor components at issue here were not themselves released in the past under the GNU AGPL and so there's no problem with the Only Office Team refusing to make those components available here in the AGPL-licensed repository. But it is a violation of the existing AGPL 3.0 to do more than that, as they did -- to turn on a new SaaSS forced licensing of closed source so that every user and every developer finds they are no longer free to find or create their own replacement editor components if they wish.

FYI, the iOS mobile App source code has been impacted negatively by this, as well, and no longer builds because of the missing editor components. https://github.com/ONLYOFFICE/documents-app-ios

It was not difficult to remove the dependencies in the Podfile and Xcode, but it's very disappointing to see the Only Office Team making a serious and avoidable mistake after all these years of high-quality free software development. I appreciate how challenging it is to be ignored by the industry the way Only Office has been. And there is extreme hostility, irrational hostility, toward the GNU AGPL specifically, with completely false narratives from influential people dominating the debate for the last decade. The misinformation campaign and the hostility toward GNU Affero-licensed works has succeeded in suppressing use of GNU AGPL almost completely, and this is a catastrophic loss for all of humanity that in my opinion the Only Office Team should just confront head-on and fix for all of us by powering through the resistance and misinformation instead of adding to it as they decided to do at the beginning of the pandemic in March 2020.

see: https://opensource.google/docs/using/agpl-policy/

The following statement by Google is FALSE, and serves only to suppress the creation of open source and free software that Google cannot use on their servers and modify to derive Google cloud computing services without being required to give copies of their modified open source code back to the community from which it (and Google itself) came:

```
WARNING: Code licensed under the GNU Affero General Public License ([AGPL](https://en.wikipedia.org/wiki/GNU_Affero_General_Public_License))
MUST NOT be used at Google.

The license places restrictions on software used over a network which are extremely difficult for Google
to comply with.

Using AGPL software requires that anything it links to must also be licensed under the AGPL.
```

I hope this helps explain what the problem is. You might remember, depending on how old you are, that Microsoft similarly attacked the GNU GPL during the 1990s, making vicious false statements exactly like the ones made by Google.

Microsoft nearly went out of business because of that mistake. If they had not changed their policy to officially endorse and support open source and free software in the last 20 years then it's possible Microsoft would no longer exist.

The Only Office Team should learn from history and do the right thing instead of repeating the mistakes of the past. 🙏

**Comment by JasonCoombs** [comment]
see also https://www.gnu.org/licenses/why-affero-gpl.html

**Comment by ShockwaveNN** [comment]
Ok, I'll agree with some of your points (not all of them), but I'm not in a position to make such a decision. 

I'll show this PR to our management team

**Comment by Galegod** [comment]
> Only Office Team cannot insert into the AGPL-licensed repository the lines of source code they inserted which disable functionality and impose a forced private licensing scheme. Apparently the four editor components at issue here were not themselves released in the past under the GNU AGPL and so there's no problem with the Only Office Team refusing to make those components available here in the AGPL-licensed repository. But it is a violation of the existing AGPL 3.0 to do more than that, as they did -- to turn on a new SaaSS forced licensing of closed source so that every user and every developer finds they are no longer free to find or create their own replacement editor components if they wish. <

Not sure I get the idea. We comply with AGPL v3 at all the points. 
I see you do not like the situation that one specific thing is not available for Community version. But I hope we are still doing a great job and ONLYOFFICE can be definitely used according the license type chosen.

**Comment by JasonCoombs** [comment]
> Not sure I get the idea. We comply with AGPL v3 at all the points. I see you do not like the situation that one specific thing is not available for Community version. But I hope we are still doing a great job and ONLYOFFICE can be definitely used according the license type chosen.


Can we please keep the issue open while there is a discussion about the correct resolution to this?

Perhaps the right solution is for the ONLYOFFICE Team to turn control of this repository over to outside developers, and for there to be a fork "ONLYOFFICE PREMIUM" or whatever your team chooses for the branding for the commercial edition.

Analogous to CHROME which is a product built by Google from the Chromium open source project.

See discussion of these issues, and how the open source industry is failing to understand good models for solving this problem, in the discussion on Reddit here:

https://www.reddit.com/r/selfhosted/comments/fpurk6/stop_recommending_onlyoffice/

and, in this article which ONLYOFFICE Team linked to from your Medium blog: (note that this article says repeatedly that the management teams of other open source projects think the ENTIRE problem would be solved if they had done as ONLY OFFICE did and apply the GNU Affero license instead of the license they did choose because only the Affero license ensures that developers who build hosted applications in the cloud are still bound by the terms of the license agreement and must release to the public their modifications to the free and open source software)

https://www.geekwire.com/2018/open-source-companies-considering-closed-approach/

Note, also, that in your Medium blog post you end the article with this invitation to discuss, but there are no Comments:

https://medium.com/@onlyoffice/answers-to-all-your-questions-about-mobile-onlyoffice-e19eefd7b7c2
```
"Let’s discuss!
Yes, we said all questions. Now it’s your turn to ask what we missed to make this article even more
complete with your comments."
```

I believe your team needs to approach this entire subject differently.

The problem is the way you are governing. It's easy to solve. The two simplest solutions are:

1. ONLYOFFICE Team forks the existing AGPL-licensed repositories for its commercial product with mobile editing feature enabled, which it releases under its own license, and you turn control of the AGPL-licensed repositories over to the public, or,
2. ONLYOFFICE TEAM stops trying to solve its financial problem by abandoning the AGPL and instead you make it clear to the public that you are fully-committed to building a Free Software future for all cloud computing and the future of the Internet.

In my opinion, Option 2 is better for you and better for everyone. Please choose Option 2. Accept my Pull Request so that the mistake that you made is reverted, and restore the editor components and release the source code under the AGPL 3.0 so that your small community of supporters and customers has the ability to become a very large community and every ethical and reasonable path to financial reward for the ONLYOFFICE Team can be explored and developed.

If you are not aware that ONLYOFFICE Team could create a blockchain and join the modern world of crypto finance then you are missing the entire economic value of what you have created and there's no hope for you in the future anyway so it won't matter which choice you make.

**Comment by JasonCoombs** [comment]
also, you do not seem to be aware that ONLYOFFICE Team is essentially the ONLY development team in the entire world that still exists after choosing the GNU Affero license.

look what happened to Berkeley DB at Oracle.

https://www.oracle.com/database/technologies/related/berkeleydb.html

people declared Berkeley DB "dead" as soon as Oracle converted to the GNU Affero license.

https://twitter.com/berkeleydb?lang=en

image

the reason this happened was that people like Google were spreading lies about the Affero license.

just like Microsoft did (coming primarily from the evil genius, Steve Ballmer) before when trying to fight Linux and Apple, and suppress Free Software, people lied about the GNU Affero license claiming it was a "virus" that would "infect" everything it touched by REMOVING rather than PROTECTING freedoms.

everyone who understands the truth knows that ONLY the Affero license PROTECTS freedoms.

the ONLYOFFICE Team is the last team standing, but sadly it appears you also do not understand freedom.

the people who do understand freedom are now building a new future that will deny commercial success to those who do not value freedom, development teams that do not help their users achieve freedom and opportunity in every way possible.

**Pull request closed without merging**
