### PR TITLE
Feature/translation zh tw

### PR DESCRIPTION
**Pull request by shooding**
Use more localized phrases.

### CODE REVIEW

**Comment by svetlana81** [comment]
Hello.
We are currently reviewing your changes. When verification is completed, we will move your changes to our internal translation system.
Thank you for your collaboration.
Best regards.

**Comment by Maria-Sukhova** [comment]
The concerned translations have been verified and edited within ONLYOFFICE Translation System and are going to be updated on Github.

**Comment by Maria-Sukhova** [comment]
Hello.
The concerned translations have been verified and edited within ONLYOFFICE Translation System and are going to be updated on Github.
Thank you for your collaboration.
Best regards.

**Comment by JuliaRadzhabova** [comment]
Translations updated

**Pull request closed without merging**
