### PR TITLE
Optimized assets.

### PR DESCRIPTION
**Pull request by K0-RR**
Lossless compression done by using oxipng.
This will result in a smaller app package size.
I have already done this to the `desktop-apps`, `core`, and `sdkjs` repositories but I wanted to hear Your opinions first before opening the rest of the prs. The biggest differences were in this repository. I'm currently redoing this optimization with zopfli algorithm for better results but this takes about 20x more time. The differences should be about 7% less though.

### CODE REVIEW

**Comment by ShockwaveNN** [comment]
@maxkadushkin please take a look

Personally I'm not that good aware how our build process for those images are organized, but I think reduction should on build step, not on resources itself

Since as soon as our design team update some icons - the should not to forget to use `oxipng` on them

But I maybe incorrect

**Comment by maxkadushkin** [comment]
@RDKRACZ , thanks for you work! in general, in that repo we use [grunt-contrib-imagemin](https://github.com/gruntjs/grunt-contrib-imagemin) plugin to compress images during build process. but it's an interesting research about the tool you are using and results

**Review by maxkadushkin — COMMENTED** [review]
we use grunt-contrib-imagemin plugin to compress images during build process

**Comment by K0-RR** [comment]
> in that repo we use [grunt-contrib-imagemin](https://github.com/gruntjs/grunt-contrib-imagemin)

Seems like grunt-contrib-imagemin is no longer maintained but setting png optimization level to 7 (not sure which level You currently use and how much more time it will take with 7) should give nearly (because it uses optipng instead oxi) the same results as these in this pr.
https://github.com/gruntjs/grunt-contrib-imagemin#optimizationlevel-png

What about other mentioned repos? Is grunt-contrib-imagemin used there too?

**Comment by maxkadushkin** [comment]
> What about other mentioned repos? Is grunt-contrib-imagemin used there too?

no, image compress plugins are not used during compile process in repos desktop-apps and sdkjs

**Pull request closed without merging**
